# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: de623ee7aa1fcf547b4f8a3634147dfdba1263d9808d62492657a42c139b81c6495d5c8788858703ac7475aa6b911e8253d45655768aafddb6216d7fd2ecba56

test:
  secret_key_base: 7987a4e120111cb4958433f3a09074a43a69c956f0ee81a5d867552376b7ebd1e82c8f27edd9743ca33ab8a5fcfda1fbb25025568055cfe728109563791df83c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
